from pathlib import Path
import os

PATH_DATA_DIR = Path("data")
PATH_ASSETS_DIR = Path("assets")
PATH_IMAGES_DIR = PATH_ASSETS_DIR / "images"
PATH_FONTS = PATH_ASSETS_DIR / "fonts"
PATH_PLOTS_DIR = PATH_ASSETS_DIR / "plots"

PATH_PYTHON_ICON = PATH_IMAGES_DIR / "python_icon.png"
PDF_EXTENSION = ".pdf"
ENV_FOLDER_DATA = "FOLDER_DATA"
ENV_PHOTO_NAME = "PHOTO_NAME"

FOLDER_DATA = os.getenv(ENV_FOLDER_DATA)
PHOTO_NAME = os.getenv(ENV_PHOTO_NAME)

if not FOLDER_DATA:
    raise RuntimeError(f"La variable de entorno '{ENV_FOLDER_DATA}' es requerida.")
if not PHOTO_NAME:
    raise RuntimeError(f"La variable de entorno '{ENV_PHOTO_NAME}' es requerida.")


PATH_FOLDER_DATA = PATH_DATA_DIR / FOLDER_DATA
PATH_LINKEDIN_PROFILE = PATH_FOLDER_DATA / "Profile.csv"
PATH_LINKEDIN_POSITIONS = PATH_FOLDER_DATA / "Positions.csv"
PATH_LINKEDIN_EDUCATION = PATH_FOLDER_DATA / "Education.csv"
PATH_PHOTO = PATH_IMAGES_DIR / PHOTO_NAME
PATH_PDF_BASENAME = PATH_FOLDER_DATA.stem

PATH_PDF_OUTPUT = PATH_DATA_DIR / f"{PATH_FOLDER_DATA.stem}{PDF_EXTENSION}"
